import type { Metadata } from "next";
import {Playfair_Display, Source_Code_Pro  } from 'next/font/google'
import "./globals.css";
import Providers from "@/components/providers";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";



const sans = Source_Code_Pro({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
        className={cn(
          'flex min-h-screen flex-col font-sans antialiased',
          sans.variable,
          playfair.variable
        )}
      >
        <Providers>
          <Header />
          <main className="grow">
          {children}
          </main>
          <Footer />
          </Providers>
        
      </body>
    </html>
  );
}
